export const SEARCH_BY_TEXT = 'SEARCH_BY_TEXT';
export const SEARCH_SMART_LINK_SUCCESS = 'SEARCH_SMART_LINK_SUCCESS';
export const SEARCH_SMART_LINK_FAILURE = 'SEARCH_SMART_LINK_FAILURE';

export const SHOW_PRODUCT_DETAILS = 'SHOW_PRODUCT_DETAILS';

export const SELECTED_CRITERIA = 'SELECTED_CRITERIA';
export const DELETE_CRITERIA = 'DELETE_CRITERIA';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAILURE = 'GET_PRODUCT_DETAILS_FAILURE';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST';

export const SHOW_ADVANCED_SEARCH = 'SHOW_ADVANCED_SEARCH';
export const SET_ADVANCED_SEARCH ='SET_ADVANCED_SEARCH';


export const ADVANCED_SEARCH_BEGIN = 'ADVANCED_SEARCH_BEGIN';
export const ADVANCED_SEARCH_SUCCESS = 'ADVANCED_SEARCH_SUCCESS';
export const ADVANCED_SEARCH_FAILURE = 'ADVANCED_SEARCH_FAILURE';


