export const SEARCH_SAGE_CATEGORY = 'SEARCH_SAGE_CATEGORY';
export const SEARCH_SAGE_CATEGORY_SUCCESS = 'SEARCH_SAGE_CATEGORY_SUCCESS';
export const SEARCH_SAGE_CATEGORY_FAILURE = 'SEARCH_SAGE_CATEGORY_FAILURE';


export const SEARCH_SAGE_THEME = 'SEARCH_SAGE_THEME';
export const SEARCH_SAGE_THEME_SUCCESS = 'SEARCH_SAGE_THEME_SUCCESS';
export const SEARCH_SAGE_THEME_FAILURE = 'SEARCH_SAGE_THEME_FAILURE';


export const SEARCH_SAGE_SORTBY = 'SEARCH_SAGE_SORTBY';
export const SEARCH_SAGE_SORTBY_SUCCESS = 'SEARCH_SAGE_SORTBY_SUCCESS';
export const SEARCH_SAGE_SORTBY_FAILURE = 'SEARCH_SAGE_SORTBY_FAILURE';

export const SEARCH_SAGE_PRODUCTS = 'SEARCH_SAGE_PRODUCTS';
export const SEARCH_SAGE_PRODUCTS_SUCCESS = 'SEARCH_SAGE_PRODUCTS_SUCCESS';
export const SEARCH_SAGE_PRODUCTS_FAILURE = 'SEARCH_SAGE_PRODUCTS_FAILURE';
export const SELECT_PRODUCT_BY_ID ='SELECT_PRODUCT_BY_ID';

export const SEARCH_PRODUCTS_INHOUSE ='SEARCH_PRODUCTS_INHOUSE';